"""empty message

Revision ID: 2273b374ba98
Revises: None
Create Date: 2016-10-29 23:22:08.540335

"""

# revision identifiers, used by Alembic.
revision = '2273b374ba98'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('venues', sa.Boolean(), nullable=True),
    sa.Column('caterers', sa.Boolean(), nullable=True),
    sa.Column('audio_visual', sa.Boolean(), nullable=True),
    sa.Column('stylist_decor', sa.Boolean(), nullable=True),
    sa.Column('event_planner', sa.Boolean(), nullable=True),
    sa.Column('entertainment', sa.Boolean(), nullable=True),
    sa.Column('photographer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('nr_persons', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('event_type')
    ### end Alembic commands ###
