"""empty message

Revision ID: 38979266200f
Revises: 2273b374ba98
Create Date: 2016-10-30 12:47:55.843065

"""

# revision identifiers, used by Alembic.
revision = '38979266200f'
down_revision = '2273b374ba98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vendor_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contacts', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vendor_type_id'], ['vendor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'event', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'event_type', ['event_type_id'], ['id'])
    op.drop_column(u'event', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'event', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'event_type', ['user_id'], ['id'])
    op.drop_column(u'event', 'event_type_id')
    op.drop_table('vendor')
    op.drop_table('vendor_type')
    ### end Alembic commands ###
